version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bdhabi
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/BDHabi.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - etl_network

  etl_service:
    build: ./proyectoETL
    container_name: etl_container
    command: sh -c "./wait-for-it.sh mysql:3306 -- sleep 60 && python ./main.py"
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456789
      - MYSQL_DATABASE=bdhabi
      - MYSQL_PORT=3306
    volumes:
      - ./proyectoETL/source:/proyectoETL/source
      - ./proyectoETL/target:/proyectoETL/target
    networks:
      - etl_network

networks:
  etl_network:
